apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: sv-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-deploy
      app: sv-web
  template:
    metadata:
      name: mysql-deploy
      labels:
        name: mysql-deploy
        app: sv-web
    spec:
      containers:
        - name: mysql 
          image: mysql:5.5
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "mysql"
            - name: MYSQL_ROOT_PASSWORD
              value: "proxxi"
            - name: MYSQL_USER
              value: "root"


