apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    name: wordpress-deploy
    app: sv-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-deploy
      app: sv-web
  template:
    metadata:
      name: wordpress
      labels:
        name: wordpress-deploy
        app: sv-web
    spec:
      containers:
        - name: wordpress-pod
          image: wordpress:4.7-php5.6
          ports:
          - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "10.244.0.63"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              value: "proxxi"
    
    
