apiVersion: v1 
kind: Service
metadata:
  name: wp-service
  labels:
    name: wp-service
    app: sv-web
spec:
  type: NodePort
  selector:
    name: wp-pod 
    app: sv-web 
  ports:
  - port: 80
    targetPort: 80